insert into Audit_Question values(1,'Internal','Have all Change requests followed SDLC before PROD move?','NO');
insert into Audit_Question values(2,'Internal','Have all Change requests been approved by the application owner? ','NO');
insert into Audit_Question values(3,'Internal','Are all artifacts like CR document, Unit test cases available? ','NO');
insert into Audit_Question values(4,'Internal','Is the SIT and UAT sign-off available? ','NO');
insert into Audit_Question values(5,'Internal','Is data deletion from the system done with application owner approval? ','NO');
insert into Audit_Question values(6,'SOX','Have all Change requests followed SDLC before PROD move?','NO');
insert into Audit_Question values(7,'SOX','Have all Change requests been approved by the application owner? ','NO');
insert into Audit_Question values(8,'SOX','For a major change, was there a database backup taken before and after PROD move? ','NO');
insert into Audit_Question values(9,'SOX','Has the application owner approval obtained while adding a user to the system? ','NO');
insert into Audit_Question values(10,'SOX','Is data deletion from the system done with application owner approval? ','NO');